package com.vendorsphere.notification;

public enum NotificationEvent {

    PURCHASE_REQUEST_SUBMITTED,
    PURCHASE_REQUEST_APPROVED,
    PURCHASE_REQUEST_REJECTED,
    VENDOR_INVITED_TO_RFQ,
    RFQ_CLOSING_WITHIN_24_HOURS,
    QUOTATION_SUBMITTED,
    VENDOR_SELECTED,
    PURCHASE_ORDER_ISSUED,
    DELIVERY_RECORDED,
    INVOICE_SUBMITTED,
    INVOICE_APPROVED,
    INVOICE_REJECTED,
    PAYMENT_RECORDED,
    INVOICE_MATCH_EXCEPTION_RAISED,
    OVERDUE_DELIVERY_DETECTED,
    VENDOR_DOCUMENT_EXPIRING,

    RFQ_CANCELLED
}
